@extends('layouts.app')
@section('content')
<div class="topbar"><div><h1>App IP Pools · {{ $mikrotikRouter->name }}</h1><div class="muted">এখানকার তালিকাটি App-এ save করা master IP pool। নিচে MikroTik থেকে আনা আলাদা snapshot আছে।</div></div><div class="actions"><form method="post" action="{{ route('mikrotik-routers.import.ip-pools', $mikrotikRouter) }}">@csrf<button class="btn secondary">Refresh MikroTik Pools</button></form><a class="btn light" href="{{ route('mikrotik-routers.compare', $mikrotikRouter) }}">Compare</a><a class="btn light" href="{{ route('mikrotik-routers.show', $mikrotikRouter) }}">Back</a></div></div>
<form class="card form-grid" method="post" action="{{ route('mikrotik-routers.pools.store', $mikrotikRouter) }}" style="margin-bottom:16px">@csrf
    <div><label>Pool name</label><input name="name" required></div><div><label>Ranges</label><input name="ranges" placeholder="10.0.0.2-10.0.0.254" required></div><div><label>Next pool</label><input name="next_pool"></div><div><label>App note</label><input name="notes"></div><div class="full"><button class="btn" type="submit">Add to App IP Pools</button></div>
</form>
<section class="card" style="margin-bottom:16px"><h2>Saved in App</h2><table><thead><tr><th>Name</th><th>Ranges</th><th>Next pool</th><th>Note</th><th>Status</th><th>Action</th></tr></thead><tbody>
@forelse($pools as $pool)<tr><td><strong>{{ $pool->name }}</strong></td><td>{{ $pool->ranges }}</td><td>{{ $pool->next_pool ?: '—' }}</td><td>{{ $pool->notes ?: '—' }}</td><td><span class="badge {{ $pool->status }}">{{ $pool->status }}</span></td><td><div class="actions"><details><summary class="btn light">Edit</summary><form method="post" action="{{ route('mikrotik-routers.pools.update', [$mikrotikRouter,$pool]) }}" style="margin-top:8px;min-width:260px">@csrf @method('PATCH')<input name="name" value="{{ $pool->name }}"><input name="ranges" value="{{ $pool->ranges }}"><input name="next_pool" value="{{ $pool->next_pool }}"><input name="notes" value="{{ $pool->notes }}"><select name="status"><option value="active" @selected($pool->status==='active')>Active</option><option value="inactive" @selected($pool->status==='inactive')>Inactive</option></select><button class="btn light">Save</button></form></details><form method="post" action="{{ route('mikrotik-routers.pools.export', [$mikrotikRouter,$pool]) }}">@csrf<button class="btn secondary">Export to MikroTik</button></form><form method="post" action="{{ route('mikrotik-routers.pools.destroy', [$mikrotikRouter,$pool]) }}" onsubmit="return confirm('Delete this App IP pool? MikroTik will not be changed.')">@csrf @method('DELETE')<button class="btn danger">Delete</button></form></div></td></tr>
@empty<tr><td colspan="6">No IP pool saved in the app yet.</td></tr>@endforelse
</tbody></table><div style="margin-top:16px">{{ $pools->links() }}</div></section>
<section class="card"><h2>MikroTik Pool Snapshot</h2><div class="muted" style="margin-bottom:8px">Router থেকে import করা pool। প্রয়োজন হলে প্রতিটি pool App master list-এ save করুন।</div><table><thead><tr><th>Name</th><th>Ranges</th><th>Next pool</th><th>Router note</th><th>Action</th></tr></thead><tbody>@forelse($mikrotikPools as $pool)<tr><td>{{ $pool->name }}</td><td>{{ $pool->ranges ?: '—' }}</td><td>{{ $pool->next_pool ?: '—' }}</td><td>{{ $pool->source_note ?: '—' }}</td><td><form method="post" action="{{ route('mikrotik-routers.imported-pools.save-to-app',[$mikrotikRouter,$pool]) }}">@csrf<button class="btn light">Save to App</button></form></td></tr>@empty<tr><td colspan="5">No MikroTik pool imported yet.</td></tr>@endforelse</tbody></table></section>
@endsection
