@extends('layouts.app')

@section('content')
<style>
    .expense-hero{padding:26px;border-radius:18px;background:linear-gradient(135deg,#064e3b 0%,#059669 58%,#22c55e 100%);color:#fff;box-shadow:0 18px 45px rgba(5,150,105,.2);margin-bottom:18px}.expense-hero-top{display:flex;justify-content:space-between;align-items:flex-start;gap:18px;flex-wrap:wrap}.expense-hero h1{margin:8px 0 6px;font-size:clamp(24px,4vw,36px);line-height:1.15}.expense-hero .muted{color:#d1fae5}.expense-status{display:inline-flex;padding:7px 12px;border-radius:999px;font-size:12px;font-weight:900;letter-spacing:.06em;text-transform:uppercase;background:rgba(255,255,255,.16);border:1px solid rgba(255,255,255,.35)}.expense-hero .btn{border-color:rgba(255,255,255,.55)}.expense-hero .btn.light{background:#fff;color:#065f46}.expense-hero .btn.secondary{background:rgba(255,255,255,.13);color:#fff}.expense-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-top:22px}.expense-metric{padding:14px;border-radius:13px;background:rgba(255,255,255,.12);border:1px solid rgba(255,255,255,.18)}.expense-metric span{display:block;color:#d1fae5;font-size:12px;font-weight:800;text-transform:uppercase}.expense-metric strong{display:block;margin-top:5px;font-size:20px}.expense-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 22px}.expense-row{padding:15px 0;border-bottom:1px solid var(--line)}.expense-row span{display:block;color:var(--muted);font-size:12px;font-weight:800;text-transform:uppercase;margin-bottom:5px}.expense-note{padding:16px;border-radius:12px;background:#f8fafc;border:1px solid var(--line);white-space:pre-wrap;line-height:1.65}.draft-callout{padding:13px 15px;border-radius:12px;background:#fffbeb;border:1px solid #fde68a;color:#92400e;margin-bottom:16px}.final-callout{padding:13px 15px;border-radius:12px;background:#ecfdf5;border:1px solid #a7f3d0;color:#065f46;margin-bottom:16px}@media(max-width:780px){.expense-metrics,.expense-grid{grid-template-columns:1fr 1fr}}@media(max-width:520px){.expense-metrics,.expense-grid{grid-template-columns:1fr}.expense-hero{padding:20px}}
</style>

<section class="expense-hero">
    <div class="expense-hero-top"><div><span class="expense-status">{{ $expense->isFinalized() ? 'Finalized' : 'Editable Draft' }}</span><h1>{{ \App\Models\VehicleExpense::CATEGORIES[$expense->category] ?? ucfirst(str_replace('_',' ',$expense->category)) }}</h1><div class="muted">{{ $expense->vehicle->registration_no }} — {{ $expense->vehicle->name }}</div></div>
        <div class="actions">@if(!$expense->isFinalized())<a class="btn light" href="{{ route('fleet.expenses.edit',$expense) }}">Edit Draft</a><form method="post" action="{{ route('fleet.expenses.finalize',$expense) }}" onsubmit="return confirm('Finalize this expense? It cannot be edited afterward.');">@csrf<button class="btn secondary">Final & Lock</button></form>@endif<a class="btn secondary" href="{{ route('fleet.show',$expense->vehicle) }}">Back to Vehicle</a></div>
    </div>
    <div class="expense-metrics"><div class="expense-metric"><span>Expense Date</span><strong>{{ $expense->expense_date->format('Y-m-d') }}</strong></div><div class="expense-metric"><span>Amount</span><strong>{{ number_format((float)$expense->amount,2) }}</strong></div><div class="expense-metric"><span>Quantity</span><strong>{{ $expense->quantity ? rtrim(rtrim(number_format((float)$expense->quantity,3,'.',''),'0'),'.').' '.($expense->unit??'') : 'N/A' }}</strong></div><div class="expense-metric"><span>Mileage</span><strong>{{ $expense->mileage!==null ? number_format($expense->mileage).' km':'N/A' }}</strong></div></div>
</section>

@if($expense->isFinalized())<div class="final-callout"><strong>Finalized and locked.</strong> Finalized by {{ $expense->finalizer?->name ?? 'N/A' }} on {{ $expense->finalized_at->format('Y-m-d h:i A') }}.</div>@else<div class="draft-callout"><strong>This expense is still a draft.</strong> You can edit it and every previous version will remain in Edit History.</div>@endif

<section class="card">
    <div class="topbar" style="margin-bottom:4px"><div><h2>Expense Details</h2><div class="muted">Complete payment and trip information</div></div><a class="btn light" href="{{ route('fleet.reports.expenses',['vehicle_id'=>$expense->vehicle_id]) }}">Expense Report</a></div>
    <div class="expense-grid"><div class="expense-row"><span>Driver / Employee</span><strong>{{ $expense->employee?->name ?? 'N/A' }}</strong></div><div class="expense-row"><span>Trip Reference</span><strong>{{ $expense->trip_reference ?? 'N/A' }}</strong></div><div class="expense-row"><span>Vendor</span><strong>{{ $expense->vendor ?? 'N/A' }}</strong></div><div class="expense-row"><span>Entered By</span><strong>{{ $expense->creator?->name ?? 'N/A' }}</strong></div><div class="expense-row"><span>Entry Time</span><strong>{{ $expense->created_at?->format('Y-m-d h:i A') ?? 'N/A' }}</strong></div><div class="expense-row"><span>Last Updated</span><strong>{{ $expense->updated_at?->format('Y-m-d h:i A') ?? 'N/A' }}</strong></div></div>
    <div style="margin-top:18px"><label>Description</label><div class="expense-note">{{ $expense->description ?? 'N/A' }}</div></div>
</section>

@include('partials.record_versions', ['versions'=>$versions])
@endsection
